version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq-service"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./data/log:/var/log/rabbitmq
    env_file:
      - .env.docker
